### ISSUE TITLE
[v2 release] TODO list

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-nest-protect#280]
- [ ] Fix open issues with cookie method
- [ ] Backwards compatibility for old authentication method
- [ ] Cancel update task during restart
- [ ] Add entity translations

t.b.c.

**Comment by jnxxx** [comment]
Looks very interesting.

May I suggest to implement an evaluation of the given cookies.

I have used the integration myself for 10 months or so using the cookie method. The first 6 months it worked like a charm with no issues. Then the authentication broke for some reason. No worries, I just tried to configure it once again. It turned out to be troublesome and worked for only short periods.
It turned out I had not cleared my cookies properly. After reading the tip in issue #272 I got them from Incognito Mode, and now it seems to work again 🤞

What I notice is the difference in amount of cookies copied from the browser.
When stealing cookeis from Incognito Mode I get the following:

- NID
- __Secure-3PSID
- __Secure-3PAPISID
- __Host-3PLSID
- __Secure-3PSIDCC

From a normal tab with improperly cleared cookies, I furthermore got:

- 1P_JAR
- CONSENT
- __Secure-3PSIDTS

To help others, could it be an idea in the config + options flow to implement a check and a warning if the are more than the needed 5 cookies?
If not possible to implement just a warning, it could simply result in an error suggesting to use the Incognito Mode. But accept it if submitting the same string a second time.
If there is no better suggestion, I can give it a try with the implementation.


Secondly, if it experiences the USER_LOGGED_OUT exception, would it be an idea to stop it from retrying?
For two reasons:
1. To avoid spamming the log
2. In case it could interfere with the user trying to set up a new session


Lastly, it seems the HTTP session contains a cookie_jar, containing cookies set by previous responses. Would it be an idea to clear this upon configuration? Simply to avoid mixing cookies from multiple sessions.
(I ended up deleting the integration and then re-adding it, utilizing config rather than options flow. Not sure if it made a difference though.)

**Comment by iMicknl** [comment]
@jnxxx thanks, good feedback! Personally I am still using the original auth method with a refresh token. The cookie method hasn't been developed by me, and the reason it isn't released yet in main, is because there are many open issues.

I just finished my work on the Overkiz (Somfy) integration in core, so hopefully the coming months I will have some more time to work on Nest Protect!
